sudo: required
language: csharp
solution: ./src/CoreTodo.sln
services:
  - docker
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      group: deprecated-2017Q4
      dotnet: 2.1.3
      mono: none
      env: DOTNETCORE=2.0
script:
  - chmod +x ./build/deploy-envs.sh
  - chmod +x ./build/scripts/build.sh
  - chmod +x ./build/scripts/deploy.sh
  - cd build/scripts
  - ./build.sh
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy.sh; fi